version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - apt-get update && apt-get install -y unzip
      - curl -fsSL https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip -o packer.zip
      - unzip packer.zip -d /usr/local/bin
  build:
    commands:
      - echo Starting AMI build process
      - packer build packer/ami-template.json
  post_build:
    commands:
      - echo AMI build completed

artifacts:
  files:
    - '**/*'
